# Generated by Django 4.2.5 on 2023-09-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerApi', '0002_alter_url_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=10, primary_key='ff8058', serialize=False),
        ),
    ]
