# Generated by Django 4.2.4 on 2023-09-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortnerApi', '0003_remove_url_id_alter_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
